stages:
  - build

build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.eelo.io:5000
    - docker build -t registry.gitlab.eelo.io:5000/eelo/docker-lineage-cicd .
    - docker push registry.gitlab.eelo.io:5000/eelo/docker-lineage-cicd:latest
  only:
    - master
